export const SERVICES = {
  TABLESCAPES: {
    slug: 'all-about-tablescapes',
    title: 'All About Tablescapes',
    subTitle:
      'Create a visually appealing and cohesive table display for your event',
    price: '$800',
    body: "Tablescapes refer to the artful arrangement of table settings, centerpieces, decor, and other design elements to create a visually appealing and cohesive table display. It's not just about putting plates and forks on a table, but it's more like creating a whole vibe or theme for the table. You might use different colors, textures, and decorations to make it look beautiful and exciting. It's a fun way to make a dinner or party feel extra special! As a company specializing in event planning, Aniah Social Events Co. can provide the expertise and creativity needed to make your event memorable with a beautiful and unique tablescape.",
    services: [
      'Professional Expertise',
      'Time-Saving',
      'Attention to Detail',
      'Customization',
    ],
    callToAction: 'Contact us today for a free quote',
  },
  PLANNING_AND_COORDINATION: {
    TRUE_DAY_OF_COORDINATION: {
      slug: 'true-day-of-coordination',
      title: 'True Day of Coordination',
      subTitle: '6 HR. MINIMUM',
      price: '$95/HR.',
      body: '',
      services: [
        'Initial Consultation: Discuss needs and preferences.',
        'Vendor Coordination: Confirm details and create vendor timeline.',
        'Wedding Timeline Creation: Develop a detailed schedule.',
        'Day-of Coordination: Oversee setup, manage timeline, address issues.',
        'Emergency Assistance: Handle unforeseen challenges.',
        'Guest Management: Assist with seating and directions.',
        'Ceremony and Reception Management: Ensure smooth flow of events.',
      ],
    },
    THIRTY_DAYS_OUT_COORDINATION: {
      slug: '30-days-out-coordination',
      title: '30-Days Out Coordination',
      subTitle: '',
      price: '$1000',
      body: 'Everything included in True day of Coordination +',
      services: [
        'Rehearsal Coordination: Organize and direct the rehearsal.',
        'Minimal Decor Setup: Provide assistance with setting up minimal decor elements such as centerpieces, place settings, and any other tabletop decor items.',
        'Cleanup: Assist with breakdown, ensuring items are returned properly and rentals are accounted for.',
      ],
    },
    PARTIAL_PLANNING: {
      slug: 'partial-planning',
      title: 'Partial Planning',
      subTitle: '',
      price: '$1,800',
      body: 'Everything included in True Day of & 30-days out Coordination +',
      services: [
        'Initial Consultation: Review existing plans and identify needs.',
        'Vendor Recommendations and Coordination: Assist with securing remaining vendors.',
        'Timeline Creation and Management: Develop a comprehensive schedule.',
        'Venue Coordination: Finalize logistics and preferences with the venue.',
        'Decor and Design Assistance: Offer guidance and coordinate decor elements.',
        'RSVP Tracking and Guest Management: Manage RSVPs and seating arrangements.',
        'Wedding Rehearsal Coordination: Organize and oversee the rehearsal.',
        'Day-of Coordination: Provide on-site coordination for a smooth event.',
        'Emergency Assistance: Handle unforeseen challenges efficiently.',
        'Monthly Virtual meetings',
      ],
    },
    FULL_PLANNING: {
      slug: 'full-planning',
      title: 'Full Planning',
      subTitle: '',
      price: '$2,600',
      body: 'Everything included in True Day of, 30-days out, & Partial Planning +',
      services: [
        'Design & Decor Assistance: Offer guidance on decor and theme.',
        'Guest Management: Assist with guest lists and RSVP tracking.',
        'Budget Management: Assist in budget creation and allocation.',
        'Post-Wedding Wrap-Up: Assist with vendor payments and wrap-up tasks.',
        'Additional Consultations: Offer ongoing support and guidance.',
      ],
    },
  },
};
