const DATA = [
  {
    slug: 'social-affair',
    title: 'Social Affair',
    subTitle: 'Rehearsal & Wedding Day Coordination',
    price: '$95/HR. MINIMUM 8 hrs.',
    body: 'With our "Social Affair" package, you can rest assured that your wedding will run smoothly and you can focus on enjoying your special day',
    services: [
      'Rehearsal Management (2 Hrs.)',
      'Ceremony Management (6 Hrs. consecutively)',
      'Initial consultation to discuss your wedding vision and get a sense of your planning progress to date',
      'A broad Timeline and execution of the timeline',
      'Vendor coordination, including confirmations and logistics management',
      'Access to our emergency kit in case of any last-minute mishaps',
    ],
  },
  {
    slug: 'socially-chic',
    title: 'Socially Chic',
    subTitle: '40-Days Out',
    price: '$800',
    body: 'Our "Socially Chic" package is perfect for couples who have already planned most of their wedding and need extra help in the final few weeks leading up to their big day. With this 40-day event coordination package, we\'ll step in and take care of all the logistical details, allowing you to relax and enjoy the last few weeks of your engagement.',
    services: [
      'Initial consultation to discuss your wedding vision and get a sense of your planning progress to date',
      'A detailed timeline and schedule of events for your wedding day',
      'Vendor coordination, including confirmations and logistics management',
      'A final walk-through of your venue to ensure everything is in place for your big day',
      'On-site coordination for your ceremony and reception, including management of the timeline and vendors',
      'Access to our emergency kit in case of any last-minute mishaps',
    ],
  },
  {
    slug: 'social-soiree',
    title: 'Social Soiree',
    subTitle: 'Partial Planning & Day of Coordination',
    price: '$1,600',
    body: 'Our "Social Soiree" package is designed for couples who have already started planning their wedding but are overwhelmed and need guidance and support. With this partial planning package, we\'ll work with you to ensure that your vision for your wedding day is brought to life while taking care of the logistical details and providing expert advice along the way.',
    services: [
      'Initial consultation to discuss your wedding vision and get a sense of your planning progress to date',
      'Assistance with vendor selection and management, including negotiating contracts and reviewing proposals',
      'Development of a comprehensive wedding timeline and schedule of events',
      'Recommendations and guidance on decor, design, and theme',
      'On-site coordination and management of your wedding rehearsal',
      'Coordination of your wedding ceremony and reception, including management of vendors and timeline',
    ],
  },
  {
    slug: 'socially-atelier',
    title: 'Social Atelier',
    subTitle: 'Start-to-finish planning & Coordination',
    price: '$2,400',
    body: 'Our "Social Atelier" package is designed for couples just beginning their wedding planning journey and feeling overwhelmed by the many decisions and details that must be managed. With this complete planning package, we\'ll work with you from start to finish to bring your vision to life and create an unforgettable wedding experience.',
    services: [
      'Initial consultation to discuss your wedding vision, style, and budget',
      'Assistance with finding the perfect venue for your wedding and negotiating contracts',
      'Vendor selection and management, including contract negotiations, reviewing proposals, and managing communications',
      'Development of a comprehensive wedding timeline and schedule of events',
      'Recommendations and guidance on decor, design, and theme',
      'Regular check-ins and updates on your wedding planning progress',
      'On-site coordination and management of your wedding rehearsal',
      'Coordination of your wedding ceremony and reception, including management of vendors and timeline',
    ],
  },
];
export default DATA;
