export const SERVICES = {
  PLANNING_AND_COORDINATION: {
    THIRTY_DAYS_OUT_COORDINATION: {
      slug: "30-days-out-coordination",
      pathname: "/services/30-days-out-coordination",
      title: "30-Days Out Coordination",
      subTitle: "",
      price: "$1,400",
      body: "Everything included in True day of Coordination +",
      services: [
        "Rehearsal Coordination: Organize and direct the rehearsal.",
        "Minimal Decor Setup: Provide assistance with setting up minimal decor elements such as centerpieces, place settings, and any other tabletop decor items.",
        "Cleanup: Assist with breakdown, ensuring items are returned properly and rentals are accounted for.",
      ],
    },
    PLANNING_AND_COORDINATION: {
      slug: "planning-and-coordination",
      pathname: "/services/planning-and-coordination",
      title: "Planning & Coordination",
      subTitle: "",
      price: "$2,000",
      body: "Everything included in 30-days Coordination +",
      services: [
        "Initial Consultation: Review existing plans and identify needs.",
        "Vendor Recommendations and Coordination: Assist with securing remaining vendors.",
        "Venue Coordination: Finalize logistics and preferences with the venue.",
        "Decor and Design Assistance: Offer guidance and coordinate decor elements.",
        "Wedding Rehearsal Coordination: Organize and oversee the rehearsal.",
        "Day-of Coordination: Provide on-site coordination for a smooth event.",
      ],
    },
    ATELIER_PLANNING_AND_COORDINATION: {
      slug: "atelier-planning-and-coordination",
      pathname: "/services/atelier-planning-and-coordination",
      title: "Atelier: Planning & Coordination",
      subTitle: "",
      price: "$3,500",
      body: "Everything included in 30-days out and Planning & Coordination +",
      services: [
        "Custom Invitation Design: Access to our Invitation Templates, 1 consultation meeting, and 1 revision meeting.",
        "Design & Decor Assistance: Access to our basic decor packages, offer guidance on decor and theme.",
        "Post-Wedding Wrap-Up: Assist with vendor follow-ups and wrap-up tasks up to 15 days after event.",
      ],
    },
    PARTY_PLANNING: {
      slug: "party-planning",
      pathname: "/services/party-planning",
      title: "Party Planning",
      subTitle: "",
      price: "Starting at  $1,600",
      body: "Everything included in Atelier Planning & Coordination +",
      services: [
        "Custom Invitation Design: Professionally designed, digital themed invitations to match your event style. Includes digital and/or printed invitations.",
        "Custom Decor Design: A comprehensive decor plan based on your theme, colors, and preferences.",
        "Decor Purchase & Rental: We handle all decor needs, including sourcing, purchasing, and renting items. We offer curated decor options for rent or purchase, ensuring your event is beautifully styled with no hassle.",
        "Setup & Breakdown: Full setup and breakdown of all rentals and decor, ensuring a seamless event experience.",
        "Event Coordination: Day-of coordination to ensure everything runs smoothly. Vendor management, timeline creation, and on-site support.",
      ],
    },
  },
};
